"""
杨振宇老师文献数据库（完整版）
================================
数据来源：完整核查报告，逐条经 API 核验并排除同名研究者。
    ★ 第一作者 ｜ ☆ 通讯/末位 ｜ ○ 合作者
可执行复现见独立项目：yang-lab-replications
"""
from __future__ import annotations

PUBLICATIONS = [
    dict(
        year=2026,
        kind='期刊论文',
        position='第',
        topic=['不确定性量化', '分割'],
        title='A voxel-wise uncertainty-guided framework for glioma segmentation using spherical projection-based U-Net and localized refinement',
        journal='Medical Physics',
        cite='53(3):e70360',
        doi='10.1002/mp.70360',
        first_author='**Yang Z**; Yang C; Zhang R; Wang C; Chen M; Yin FF',
        finding='2D nnU-Net + 球面投影做初分割与不确定性量化 → 高不确定区交 3D nnU-Net 精修 → PSO 优化融合权重；BraTS 2020（369 例）全面超越 2D/3D 基线。',
        replicate='✅ 专栏 R2（不确定性引导的完整范式）',
    ),
    dict(
        year=2026,
        kind='期刊论文',
        position='★',
        topic=['可解释AI', '影像基因组学', '预后预测'],
        title='An Explainable Deep Model for Risk Scoring and Accurate Radionecrosis Identification Following Brain Metastasis Stereotactic Radiosurgery',
        journal='International Journal of Radiation Oncology·Biology·Physics',
        cite='125(2):649–659',
        doi='10.1016/j.ijrobp.2025.11.038',
        first_author='Zhao J; Vaios E; Calabrese E; **Yang Z**; Ginn J; Gonzalez A',
        finding='在 HBNODE 上加入 LRP（逐层相关性传播）量化非影像特征贡献，重构「决策场 F」并用 ∇F=0 的局部平衡点聚合中间状态。',
        replicate='—（数学最漂亮的一篇；平台预留扩展位）',
    ),
    dict(
        year=2026,
        kind='期刊论文',
        position='○',
        topic=['深度学习架构', '放射组学方法学'],
        title='An exploratory study on integrating radiomics with vision transformers for enhancing medical imaging classification accuracy',
        journal='Medical Physics',
        cite='53(1):e70246',
        doi='10.1002/mp.70246',
        first_author='**Yang Z**; Zhang R; Zhu H; Zhang H; Wang J; Chen M; Yin FF;',
        finding='RE-ViT：把每个 patch 的手工放射组学特征与像素 embedding 平均后送进 ViT 编码器，用领域知识弥补 ViT 的数据饥渴。',
        replicate='—（需大数据与 GPU；平台在术语库解释其原理）',
    ),
    dict(
        year=2026,
        kind='期刊论文',
        position='★',
        topic=['深度学习架构', '可解释AI'],
        title='Integrating Swin Transformers and Wavelet CNNs for Hierarchical Global–Local Mammographic Image Analysis',
        journal='IEEE Transactions on Radiation and Plasma Medical Sciences',
        cite='早期访问（pp.1–1）',
        doi='10.1109/TRPMS.2026.3724585',
        first_author='Dai X; Zhang C; Zhang R; Shi K; Chen M; Wang J; Yin FF; **Ya',
        finding='Swin Transformer 抓全局形态、小波 CNN 抓局部纹理，组合成「全局—局部」分层架构用于乳腺影像。',
        replicate='—（需大数据；平台在术语库解释其原理）',
    ),
    dict(
        year=2026,
        kind='期刊论文',
        position='☆',
        topic=['合成CT', '放疗剂量学'],
        title='Knowledge-based deep residual U-Net (DRU) for synthetic CT generation using a single MR volume for frameless radiosurgery',
        journal='Journal of Applied Clinical Medical Physics',
        cite='27(1):e70343',
        doi='10.1002/acm2.70343',
        first_author='Shu X; Lu K; Zhao J; Ginn J; Kim Y; **Yang Z**; Adamson J; M',
        finding='用 DRU 从单次 MR 生成合成 CT，引入 Visible Human 解剖先验；PSNR 75±4 dB、SSIM 0.99；Gamma 通过率 95.8%（3%/1mm）。',
        replicate='✅ 专栏 R3（Gamma 指数验证步骤）',
    ),
    dict(
        year=2026,
        kind='期刊论文',
        position='○',
        topic=['图像配准'],
        title='PhysMorph: A biomechanical and image-guided deep learning framework for real-time multi-modal liver image registration',
        journal='Physics and Imaging in Radiation Oncology',
        cite='37:100906',
        doi='10.1016/j.phro.2026.100906',
        first_author='Zhang Z; Guo D; Lu K; Jiang Z; Zhong H; Yin FF; Ren L; **Yan',
        finding='有限元力学约束嵌入深度学习配准；TRE 2.2 mm、103.4 ms（传统 FEM >10 分钟）；代码开源。**他作为通讯作者。**',
        replicate='✅ 专栏 R7 / 页面「形变配准与物理合理性」',
    ),
    dict(
        year=2025,
        kind='预印本',
        position='☆',
        topic=['其他'],
        title='A Dual Radiomic and Dosiomic Filtering Technique for Locoregional Radiation Pneumonitis Prediction in Breast Cancer Patients',
        journal='arXiv',
        cite='arXiv:2508.02169（2025-08-04）',
        doi='10.48550/arXiv.2508.02169',
        first_author='**Yang Z**; Chen Q; Zhang R; Liu M; Guo F; Yang M; Tang M; Z',
        finding='arXiv API 返回；**至今未见期刊全文版**（Crossref/Europe PMC 检索无对应期刊记录）',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='期刊论文',
        position='★',
        topic=['影像基因组学', '可解释AI'],
        title='A Radiogenomic Deep Ensemble Learning Model for Identifying Radionecrosis Following Brain Metastases (BM) Stereotactic Radiosurgery in Patients With Non-small Cell Lung Cancer BM',
        journal='Advances in Radiation Oncology',
        cite='10(8):101826',
        doi='10.1016/j.adro.2025.101826',
        first_author='Zhao J; Vaios E; Calabrese E; **Yang Z**; Robertson S; Ginn ',
        finding='90 个病灶/62 例；1024 维影像深度特征与临床（D+C）或基因组（D+G，EGFR/ALK/KRAS/PD-L1）用位置编码融合。',
        replicate='✅ 专栏 R4（多源融合）',
    ),
    dict(
        year=2025,
        kind='会议摘要',
        position='○',
        topic=['其他'],
        title='A Radiomic Quantification Framework for Hyperparameter Optimization in Texture Characterization',
        journal='Medical Physics（会议摘要，2025 年 10 月期）',
        cite='52(10)',
        doi='—',
        first_author='Zhang R; Zhu H; Qian C; Sang W; Xia F; Qian K; Ni C; Lu Y; W',
        finding='Scholars@Duke pid 1708721；末位通讯；DKU 影像组学纹理参数研究',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='预印本',
        position='☆',
        topic=['其他'],
        title='A Voxel-Wise Uncertainty-Guided Framework for Glioma Segmentation Using Spherical Projection-Based U-Net and Localized Refinement in Multi-Parametric MRI',
        journal='arXiv',
        cite='arXiv:2507.15622（2025-07-21）',
        doi='10.48550/arXiv.2507.15622',
        first_author='**Yang Z**; Yang C; Zhang R; Chen M; Wang C; Yin FF',
        finding='arXiv API 返回；已正式发表（Med Phys 2026;53(3):e70360，见 A 区）',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='会议摘要',
        position='★',
        topic=['其他'],
        title='An Explainable Deep Model for Risk Scoring and Accurate Radionecrosis Identification Following Brain Metastasis Stereotactic Radiosurgery',
        journal='International Journal of Radiation Oncology·Biology·Physics（ASTRO 2025）',
        cite='123(1):S154',
        doi='10.1016/j.ijrobp.2025.06.1247',
        first_author='Zhao J; Vaios EJ; Calabrese E; **Yang Z**; Ginn J; Floyd SR;',
        finding='Crossref 作者字段含 "Z. Yang"；同一工作期刊全文见 A 区',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='预印本',
        position='○',
        topic=['其他'],
        title='An Explainable Neural Radiomic Sequence Model with Spatiotemporal Continuity for Quantifying 4DCT-based Pulmonary Ventilation',
        journal='arXiv',
        cite='arXiv:2503.23898（v1 2025-03-31，v2 2025-07-20）',
        doi='10.48550/arXiv.2503.23898',
        first_author='Zhang R; Zhu H; Zhao J; Zhang L; Yin FF; Wang C; **Yang Z**',
        finding='arXiv API 返回；**至今未见期刊全文版**，仅对应 B 区 2024 年会议摘要',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='期刊论文',
        position='☆',
        topic=['图像配准', '深度学习架构'],
        title='An Implicit Registration Framework Integrating Kolmogorov-Arnold Networks with Velocity Regularization for Image-Guided Radiation Therapy',
        journal='Bioengineering (Basel)',
        cite='12(9):1005',
        doi='10.3390/bioengineering12091005',
        first_author='Sun P; Zhang C; **Yang Z**; Yin FF; Liu M',
        finding='首次把 KAN（Jacobi 多项式构造）用于医学图像配准，对速度场主成分建模，效率提升约 70%。',
        replicate='✅ 专栏 R7（配准的物理约束思想）',
    ),
    dict(
        year=2025,
        kind='会议摘要',
        position='○',
        topic=['其他'],
        title='Biologically Guided Deep Learning for MRI-Based Brain Metastasis Outcome Prediction after Stereotactic Radiosurgery',
        journal='Medical Physics（会议摘要，2025 年 10 月期）',
        cite='52(10)',
        doi='—',
        first_author='Zhao J; Vaios E; Calabrese E; **Yang Z**; Ji H; Wang L; Lee ',
        finding='Scholars@Duke pid 1708900；Duke 放疗系脑转移 SRS',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='会议摘要',
        position='○',
        topic=['其他'],
        title='Combining Patch-Based CNN Models with Hierarchical Shapley Explanations for Breast Cancer Diagnosis',
        journal='Medical Physics（会议摘要，2025 年 10 月期）',
        cite='52(10)',
        doi='—',
        first_author='Shi K; Li Z; Wu C; Zhao J; Chen X; Wang J; Ginn J; Yin FF; W',
        finding='Scholars@Duke pid 1708963；末位通讯；DKU 医学物理可解释 AI',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='会议摘要',
        position='☆',
        topic=['其他'],
        title='Design and Evaluation of a Unified Machine Learning Model for Predicting Normal Brain Toxicity in Single-Isocenter-Multi-Target Stereotactic Radiosurgery',
        journal='International Journal of Radiation Oncology·Biology·Physics（ASTRO 2025）',
        cite='123(1):e48',
        doi='10.1016/j.ijrobp.2025.06.3383',
        first_author='Huang Z; Zhao J; Mullikin TC; Lu K; Ginn J; **Yang Z**; Xie ',
        finding='Crossref 作者字段含 "Z. Yang"；OpenAlex 机构含 Duke Kunshan；Duke 放疗系 SIMT',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='预印本',
        position='○',
        topic=['其他'],
        title='Embedding Radiomics into Vision Transformers for Multimodal Medical Image Classification',
        journal='arXiv',
        cite='arXiv:2504.10916（v1 2025-04-15，v2 2025-04-23）',
        doi='10.48550/arXiv.2504.10916',
        first_author='**Yang Z**; Zhu H; Zhang R; Zhang H; Wang J; Wang C; Chen M;',
        finding='arXiv API 返回；已正式发表（Med Phys 2026;53(1):e70246，见 A 区）',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='会议摘要',
        position='★',
        topic=['其他'],
        title='Enhancing CNN-Based Brain Metastasis Detection in MRI By Integrating Locoregional 3D Deformation Technique',
        journal='Medical Physics（会议摘要，2025 年 10 月期）',
        cite='52(10)',
        doi='—',
        first_author='Wu C; Shi K; Zhao J; Lu K; Chen M; Yin FF; Wang C; **Yang Z*',
        finding='Scholars@Duke pid 1708576；末位通讯；DKU 医学物理硕士生第一作者',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='会议摘要',
        position='☆',
        topic=['其他'],
        title='Improving Mammography Diagnosis Accuracy through Global Context and Local Lesion Integration',
        journal='Medical Physics（会议摘要，2025 年 10 月期）',
        cite='52(10)',
        doi='—',
        first_author='Dai X; Zhang C; Duan X; Zhang R; Xia F; Chen M; Yin FF; Wang',
        finding='Scholars@Duke pid 1708470；末位通讯；对应期刊论文见 A 区（IEEE TRPMS 2026）',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='会议摘要',
        position='☆',
        topic=['其他'],
        title='Predicting Brain V60% in Linac-Based Single-Isocenter-Multiple-Targets (SIMT) Stereotactic Radiosurgery Using Machine Learning',
        journal='Medical Physics（会议摘要，2025 年 10 月期）',
        cite='52(10)',
        doi='—',
        first_author='Huang Z; Zhao J; Lu K; Ginn J; **Yang Z**; Xie Y; Kim Y; Wan',
        finding='Scholars@Duke pid 1708579；Duke 放疗系 SIMT 计划质量',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='期刊论文',
        position='○',
        topic=['可解释AI', '影像基因组学'],
        title='Radiogenomic explainable AI with neural ordinary differential equation for identifying post-SRS brain metastasis radionecrosis',
        journal='Medical Physics',
        cite='52(4):2661–2674',
        doi='10.1002/mp.17635',
        first_author='Zhao J; Vaios E; **Yang Z**; Lu K; Floyd S; Yang D; Ji H; Re',
        finding='HBNODE 把影像深度特征 + 基因组标志物 + 临床参数融合进潜空间，可视化每个病例走向诊断的轨迹。',
        replicate='—（Neural ODE 需训练；平台预留扩展位）',
    ),
    dict(
        year=2025,
        kind='会议摘要',
        position='○',
        topic=['其他'],
        title='Spherical Slicing and Convolutions for Accurate Glioma Tumor Segmentation Using Multi-Parametric MRI',
        journal='Medical Physics（会议摘要，2025 年 10 月期）',
        cite='52(10)',
        doi='—',
        first_author='Zhang R; Zhu H; Zhang C; Xia R; Zhao J; Lu K; Zhang L; Wang ',
        finding='Scholars@Duke pid 1708467，NLM 完整作者列表末位为 Yang Z；DKU 医学物理',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='预印本',
        position='☆',
        topic=['其他'],
        title='Synthetic Poisoning Attacks: The Impact of Poisoned MRI Image on U-Net Brain Tumor Segmentation',
        journal='arXiv',
        cite='arXiv:2502.03825（2025-02-06）',
        doi='10.48550/arXiv.2502.03825',
        first_author='Li T; Zeng T; Zheng Y; Zhang C; Lu J; Huang H; Chu C; Yin FF',
        finding='arXiv API 返回（au:"Zhenyu Yang" 检索命中）；末位通讯，Yin Fang-Fang 合著，DKU/Duke 医学物理',
        replicate='—',
    ),
    dict(
        year=2025,
        kind='期刊论文',
        position='☆',
        topic=['放疗剂量学', '深度学习架构'],
        title='Total brain dose estimation in single-isocenter-multiple-targets (SIMT) radiosurgery via a novel deep neural network with spherical convolutions',
        journal='Medical Physics',
        cite='52(6):4266–4277',
        doi='10.1002/mp.17748',
        first_author='**Yang Z**; Khazaieli M; Vaios E; Zhang R; Zhao J; Mullikin ',
        finding='把脑「装进球里」做球面投影，用球面卷积（DeepSphere+HEALPix）预测 V50%/V60%/V66.7%；R²=0.92/0.94/0.93；参数量约 100 万，仅为 3D U-Net 的 1/30。',
        replicate='✅ 专栏 R3 / 页面「放疗剂量学工具」',
    ),
    dict(
        year=2025,
        kind='期刊论文',
        position='★',
        topic=['不确定性量化', '分割'],
        title='Uncertainty quantification in multi-parametric MRI-based meningioma radiotherapy target segmentation',
        journal='Frontiers in Oncology',
        cite='15:1474590',
        doi='10.3389/fonc.2025.1474590',
        first_author='Wang L; **Yang Z**; LaBella D; Reitman Z; Ginn J; Zhao J; Ad',
        finding='把 SPU-Net 用于 76 例脑膜瘤，用信息熵量化不确定性、Otsu 聚合；Dice 0.760 vs U-Net 0.742，HD95 2.682 vs 2.912 cm。',
        replicate='✅ 专栏 R2（信息熵 + Otsu 聚合）',
    ),
    dict(
        year=2025,
        kind='期刊论文',
        position='○',
        topic=['可解释AI'],
        title='揭开医学图像分析算法的黑箱：医学图像分析中可解释人工智能的最新进展 / Uncovering the black box of medical image analysis algorithms: recent advances in explainable AI in medical image analysis',
        journal='科学通报 Chinese Science Bulletin',
        cite='70(33):5675–5695',
        doi='10.1360/tb-2024-1299',
        first_author='**Yang Z**; Zhang R; Zhang L; Liu M; Duan X; Yin FF',
        finding='系统梳理 XAI 方法（显著性图、Grad-CAM/Score-CAM、LIME/SHAP、概念解释、因果与不确定性）在医学影像中的适用性与陷阱。**中文入门首选。**',
        replicate='✅ 平台「术语库」第 03 分册即据此整理',
    ),
    dict(
        year=2024,
        kind='会议摘要',
        position='★',
        topic=['其他'],
        title='A Dual-Radiomics Combined Model for Overall Survival Prediction in Early-Stage NSCLC Patients Using Pre-Treatment CT Images',
        journal='Medical Physics（会议摘要，2024 年 9 月期）',
        cite='51(9):6616',
        doi='—',
        first_author='Zhang R; Zhu H; Li Z; Sang W; Lu K; Wang C; Zhang L; Yin FF;',
        finding='Scholars@Duke pid 1669519；对应期刊论文见 A 区（Front Oncol 2024）',
        replicate='—',
    ),
    dict(
        year=2024,
        kind='会议摘要',
        position='☆',
        topic=['其他'],
        title='A Radiomics-Embedded Vision Transformer for Medical Image Recognition Efficiency Improvement',
        journal='Medical Physics（会议摘要，2024 年 9 月期）',
        cite='51(9):6595',
        doi='—',
        first_author='Zhu H; Wang C; Zhang R; Liu M; Guo D; Zhao H; Chen M; Yin FF',
        finding='Scholars@Duke pid 1669586，NLM 完整作者列表末位为 Yang Z；DKU 医学物理课题组',
        replicate='—',
    ),
    dict(
        year=2024,
        kind='期刊论文',
        position='☆',
        topic=['生存分析', '预后预测'],
        title='A dual-radiomics model for overall survival prediction in early-stage NSCLC patient using pre-treatment CT images',
        journal='Frontiers in Oncology',
        cite='14:1419621',
        doi='10.3389/fonc.2024.1419621',
        first_author='Zhang R; Zhu H; Chen M; Sang W; Lu K; Li Z; Wang C; Zhang L;',
        finding='手工放射组学 + 深度放射组学双路建模预测总生存（TCIA Lung1 132 例）；特征重要性与模型预测能力高度相关。**他作为通讯作者的带学生成果。**',
        replicate='✅ 专栏 R5 / 页面「特征建模与预后」',
    ),
    dict(
        year=2024,
        kind='会议摘要',
        position='☆',
        topic=['其他'],
        title='An Explainable Neural Radiomic Sequence Model with Spatiotemporal Continuity for Quantifying 4DCT-Based Pulmonary Ventilation',
        journal='Medical Physics（会议摘要，2024 年 10 月期）',
        cite='51(10):7652',
        doi='—',
        first_author='Zhang R; Zhu H; Zhao J; Zhang L; Yin FF; Wang C; **Yang Z**',
        finding='Scholars@Duke pid 1662377；末位通讯；全文见 arXiv:2503.23898',
        replicate='—',
    ),
    dict(
        year=2024,
        kind='期刊论文',
        position='☆',
        topic=['预后预测', '放疗剂量学'],
        title='Dose-Incorporated Deep Ensemble Learning for Improving Brain Metastasis Stereotactic Radiosurgery Outcome Prediction',
        journal='International Journal of Radiation Oncology·Biology·Physics',
        cite='120(2):603–613',
        doi='10.1016/j.ijrobp.2024.04.006',
        first_author='Zhao J; Vaios E; Wang Y; **Yang Z**; Cui Y; Reitman ZJ; Lafa',
        finding='把实际剂量分布信息与影像、临床特征一起送进深度集成模型。',
        replicate='✅ 专栏 R6（剂量学特征的引入）',
    ),
    dict(
        year=2024,
        kind='期刊论文',
        position='○',
        topic=['其他'],
        title='Prognostic value of different discretization parameters in ¹⁸FDG positron emission tomography radiomics of oropharyngeal squamous cell carcinoma',
        journal='Journal of Medical Imaging',
        cite='11(2):024007',
        doi='10.1117/1.JMI.11.2.024007',
        first_author='Riley BA; Stevens JB; Li X; **Yang Z**; Wang C; Mowery YM; B',
        finding='Duke 放疗系头颈癌 PET 影像组学；合作者 Mowery/Brizel/Yin/Lafata 均为 Duke',
        replicate='—',
    ),
    dict(
        year=2024,
        kind='会议摘要',
        position='○',
        topic=['其他'],
        title='Quantifying U-Net Uncertainty in MRI-Based Meningioma Segmentation for Radiotherapy',
        journal='Medical Physics（会议摘要，2024 年 9 月期）',
        cite='51(9):6600',
        doi='—',
        first_author='Wang L; **Yang Z**; LaBella D; Reitman ZJ; Ginn J; Adamson J',
        finding='Scholars@Duke pid 1669818；Duke 放疗系脑膜瘤分割',
        replicate='—',
    ),
    dict(
        year=2024,
        kind='期刊论文',
        position='○',
        topic=['不确定性量化', '分割'],
        title='Quantifying U-Net uncertainty in multi-parametric MRI-based glioma segmentation by spherical image projection',
        journal='Medical Physics',
        cite='51(3):1931–1943',
        doi='10.1002/mp.16695',
        first_author='**Yang Z**; Lafata K; Vaios E; Hu Z; Mullikin T; Yin FF; Wan',
        finding='SPU-Net：换不同球面投影中心得到多组预测，均值=分割结果、方差=不确定性图；369 例胶质瘤。',
        replicate='✅ 专栏 R2 / 页面「分割与不确定性」',
    ),
    dict(
        year=2024,
        kind='会议摘要',
        position='★',
        topic=['其他'],
        title='Radiogenomic Deep Ensemble Learning for Identifying Radionecrosis Following Brain Metastasis Stereotactic Radiosurgery (SRS)',
        journal='International Journal of Radiation Oncology·Biology·Physics（ASTRO 2024）',
        cite='120(2):S101',
        doi='10.1016/j.ijrobp.2024.07.183',
        first_author='Zhao J; Vaios EJ; **Yang Z**; Robertson SH; Ginn J; Lu K; Yi',
        finding='Crossref 作者字段含 "Z. Yang"；Duke 放疗系；Scholars@Duke pid 1659580 一致',
        replicate='—',
    ),
    dict(
        year=2024,
        kind='预印本',
        position='○',
        topic=['其他'],
        title='Single-Iso-Multiple-Targets (SIMT) Radiosurgery Plan Quality Control via a Novel Deep Neural Network with Spherical Convolutions',
        journal='Research Square',
        cite='预印本 v1',
        doi='10.21203/rs.3.rs-4488238/v1',
        first_author='**Yang Z**; Khazaieli M; Vaios E; Zhang R; Zhao J; Mullikin ',
        finding='Europe PMC（PPR 源）+ OpenAlex 收录；已正式发表（Med Phys 2025;52(6):4266-4277，见 A 区）',
        replicate='—',
    ),
    dict(
        year=2024,
        kind='学位论文/项目',
        position='★',
        topic=['其他'],
        title='放疗中腹部图像自动分割的不确定性量化与评估研究（国家自然科学基金 **青年科学基金项目**）',
        journal='国家自然科学基金委员会（NSFC）2024 年度',
        cite='—',
        doi='—',
        first_author='**杨振宇**（PI）',
        finding='昆山杜克大学官方新闻（中英文双语）明确列名 "Dr. Zhenyu Yang, Research Assistant Professor of Medical Physics" 获 NSFC 青年科学基金项目资助',
        replicate='—',
    ),
    dict(
        year=2023,
        kind='会议摘要',
        position='★',
        topic=['其他'],
        title='A Radiogenomic Machine Learning Model for Glioblastoma Post-Resection Overall Survival Group Prediction',
        journal='International Journal of Radiation Oncology·Biology·Physics（ASTRO 2023）',
        cite='117(2):S156',
        doi='10.1016/j.ijrobp.2023.06.580',
        first_author='Wang L; Vaios EJ; **Yang Z**; Zhao J; Yin FF; Reitman ZJ; Wa',
        finding='Crossref 作者字段含 "Z. Yang"；Duke 放疗系 + Reitman（Duke 神经肿瘤）',
        replicate='—',
    ),
    dict(
        year=2023,
        kind='预印本',
        position='○',
        topic=['其他'],
        title='A Radiomics-Incorporated Deep Ensemble Learning Model for Multi-Parametric MRI-based Glioma Segmentation',
        journal='arXiv',
        cite='arXiv:2303.10533（2023-03-19）',
        doi='10.48550/arXiv.2303.10533',
        first_author='Chen Y; **Yang Z**; Zhao J; Adamson J; Sheng Y; Yin FF; Wang',
        finding='arXiv API 返回；已正式发表（Phys Med Biol 2023;68(18):185025，见 A 区）',
        replicate='—',
    ),
    dict(
        year=2023,
        kind='期刊论文',
        position='○',
        topic=['分割', '可解释AI', '深度学习架构'],
        title='A neural ordinary differential equation model for visualizing deep neural network behaviors in multi-parametric MRI-based glioma segmentation',
        journal='Medical Physics',
        cite='50(8):4825–4838',
        doi='10.1002/mp.16286',
        first_author='**Yang Z**; Hu Z; Ji H; Lafata K; Vaios E; Floyd S; Yin FF; ',
        finding='用 Neural ODE（RK4 + 伴随灵敏度法）把网络行为可视化；据此判断 T1ce 是 ET/TC 的关键序列、FLAIR+T2 是 WT 的关键序列。',
        replicate='—（需 GPU 训练，平台在「术语库」与文献解读中说明）',
    ),
    dict(
        year=2023,
        kind='期刊论文',
        position='★',
        topic=['分割', '放射组学方法学'],
        title='A radiomics-incorporated deep ensemble learning model for multi-parametric MRI-based glioma segmentation',
        journal='Physics in Medicine & Biology',
        cite='68(18):185025',
        doi='10.1088/1361-6560/acf10d',
        first_author='Chen Y; **Yang Z**; Zhao J; Adamson J; Sheng Y; Yin FF; Wang',
        finding='56 个放射组学特征图经 PCA 取前 4 主成分，作为 4 个 U-Net 子模型的额外通道；4 组 softmax 叠加后用 Otsu 二值化。',
        replicate='✅ 专栏 R2（Otsu 聚合步骤）',
    ),
    dict(
        year=2023,
        kind='期刊论文',
        position='○',
        topic=['放疗剂量学', '近距离治疗'],
        title='Deep learning-based dose map prediction for high-dose-rate brachytherapy',
        journal='Physics in Medicine & Biology',
        cite='68(17):175015',
        doi='10.1088/1361-6560/acecd2',
        first_author='Li Z; **Yang Z**; Lu J; Zhu Q; Wang Y; Zhao M; Li Z; Fu J',
        finding='从「预测 DVH 汇总指标」升级为直接预测三维剂量分布图。',
        replicate='✅ 专栏 R6（剂量图思想）',
    ),
    dict(
        year=2023,
        kind='期刊论文',
        position='○',
        topic=['预后预测', '分割'],
        title='Development of a multi-feature-combined model: proof-of-concept with application to local failure prediction of post-SBRT or surgery early-stage NSCLC patients',
        journal='Frontiers in Oncology',
        cite='13:1185771',
        doi='10.3389/fonc.2023.1185771',
        first_author='**Yang Z**; Wang C; Wang Y; Lafata KJ; Zhang H; Ackerson BG;',
        finding='105 手工特征 + 512 维深度特征 + 4 项临床信息三源融合；AUC 0.742–0.825（手术）/0.888–0.920（SBRT），显著优于任何单一来源。',
        replicate='✅ 专栏 R4 / 页面「特征建模与预后」',
    ),
    dict(
        year=2023,
        kind='学位论文/项目',
        position='★',
        topic=['其他'],
        title='Explainable Artificial Intelligence Techniques in Medical Imaging Analysis（博士论文）',
        journal='Duke University（DukeSpace 机构库）',
        cite='—',
        doi='hdl:10161/27597',
        first_author='**Yang Z**',
        finding='DukeSpace REST API 检索：`dc.contributor.author = Yang, Zhenyu`，`dc.contributor.advisor = Yin, Fang-Fang`，类型 Dissertation；S',
        replicate='—',
    ),
    dict(
        year=2022,
        kind='会议摘要',
        position='★',
        topic=['其他'],
        title='A Comparative Study of Radiomics and Deep-Learning Approaches for Predicting Surgery Outcomes in Early-Stage Non-Small Cell Lung Cancer (NSCLC)',
        journal='Medical Physics（AAPM 2022 年会摘要）',
        cite='49(6):E196',
        doi='—',
        first_author='Zhang H; **Yang Z**; Ackerson B; Hu Z; Khazaieli M; Kelsey C',
        finding='Scholars@Duke pid 1817655；Duke 放疗系肺癌队列（Kelsey 为 Duke 胸放医师）',
        replicate='—',
    ),
    dict(
        year=2022,
        kind='会议摘要',
        position='○',
        topic=['其他'],
        title='A Deep Learning Model with Radiomics Analysis Integration for Glioblastoma Post-Resection Survival Prediction',
        journal='Medical Physics（AAPM 2022 年会摘要）',
        cite='49(6):E364',
        doi='—',
        first_author='Hu Z; **Yang Z**; Zhao J; Zhang H; Vaios E; Lafata K; Yin F;',
        finding='Scholars@Duke pid 1526963（WOS:000808579201118）；Duke 放疗系；全文见 arXiv:2203.05891',
        replicate='—',
    ),
    dict(
        year=2022,
        kind='预印本',
        position='○',
        topic=['其他'],
        title='A Deep Learning Model with Radiomics Analysis Integration for Glioblastoma Post-Resection Survival Prediction',
        journal='arXiv',
        cite='arXiv:2203.05891（2022-03-11）',
        doi='10.48550/arXiv.2203.05891',
        first_author='Hu Z; **Yang Z**; Zhang H; Vaios E; Lafata K; Yin FF; Wang C',
        finding='arXiv API 返回；**至今未见期刊全文版**，仅对应 B 区 AAPM 2022 会议摘要',
        replicate='—',
    ),
    dict(
        year=2022,
        kind='预印本',
        position='○',
        topic=['其他'],
        title='A Neural Ordinary Differential Equation Model for Visualizing Deep Neural Network Behaviors in Multi-Parametric MRI based Glioma Segmentation',
        journal='arXiv',
        cite='arXiv:2203.00628（v1 2022-03-01，v2 2022-03-23）',
        doi='10.48550/arXiv.2203.00628',
        first_author='**Yang Z**; Hu Z; Ji H; Lafata K; Floyd S; Yin FF; Wang C',
        finding='arXiv API 返回；已正式发表（Med Phys 2023;50(8):4825-4838，见 A 区）',
        replicate='—',
    ),
    dict(
        year=2022,
        kind='会议摘要',
        position='★',
        topic=['其他'],
        title='A Radiomics-Integrated Deep Learning Model for Identifying Radionecrosis Following Brain Metastasis Stereotactic Radiosurgery (SRS)',
        journal='International Journal of Radiation Oncology·Biology·Physics（ASTRO 2022）',
        cite='114(3):S114',
        doi='10.1016/j.ijrobp.2022.07.551',
        first_author='Zhao J; Vaios EJ; Carpenter DJ; **Yang Z**; Cui Y; Lafata K;',
        finding='Crossref 作者字段含 "Z. Yang"；Duke 放疗系（Vaios/Fecci/Floyd/Wang）',
        replicate='—',
    ),
    dict(
        year=2022,
        kind='会议摘要',
        position='○',
        topic=['其他'],
        title='A Radiomics-Integrated Deep-Learning Model for Identifying Radionecrosis Following Brain Metastasis Stereotactic Radiosurgery',
        journal='Medical Physics（AAPM 2022 年会摘要）',
        cite='49(6):E457',
        doi='—',
        first_author='Zhao J; **Yang Z**; Hu Z; Vaios E; Carpenter D; Floyd S; Laf',
        finding='Scholars@Duke pid 1526961；Duke 放疗系脑转移放射性坏死',
        replicate='—',
    ),
    dict(
        year=2022,
        kind='期刊论文',
        position='○',
        topic=['放疗剂量学', '近距离治疗'],
        title='A personalized DVH prediction model for HDR brachytherapy in cervical cancer treatment',
        journal='Frontiers in Oncology',
        cite='12:967436',
        doi='10.3389/fonc.2022.967436',
        first_author='Li Z; Chen K; **Yang Z**; Zhu Q; Yang X; Li Z; Fu J',
        finding='PCA + kNN 选相似病例 + KDE 建距离-剂量概率模型，预测膀胱/直肠 D2cc 等指标，绝对残差约 0.38–0.97 Gy。',
        replicate='✅ 专栏 R6 / 页面「放疗剂量学工具」',
    ),
    dict(
        year=2022,
        kind='期刊论文',
        position='○',
        topic=['深度学习架构'],
        title='A radiomics-boosted deep-learning model for COVID-19 and non-COVID-19 pneumonia classification using chest x-ray images',
        journal='Medical Physics',
        cite='49(5):3213–3222',
        doi='10.1002/mp.15582',
        first_author='Hu Z; **Yang Z**; Lafata KJ; Yin FF; Wang C',
        finding='用 2D 滑窗把放射组学特征做成特征图，用 VGG/DenseNet 的显著性图挑互补特征，图像+特征图联合训练；812 张胸片，50 次重复。',
        replicate='—（平台「影像实验室」可提取同族特征）',
    ),
    dict(
        year=2022,
        kind='会议摘要',
        position='○',
        topic=['其他'],
        title='Effect of PET Image Discretization On Radiomic Features of Patients Undergoing Definitive Radiotherapy for Oropharyngeal Cancer',
        journal='Medical Physics（AAPM 2022 年会摘要）',
        cite='49(6):E577–E578',
        doi='—',
        first_author='Riley B; Wang C; **Yang Z**; Mowery Y; Brizel D; Yin F; Lafa',
        finding='Scholars@Duke pid 1526965；Duke 头颈癌 PET 影像组学',
        replicate='—',
    ),
    dict(
        year=2022,
        kind='期刊论文',
        position='○',
        topic=['肺通气成像', '放射组学方法学'],
        title='Quantification of lung function on CT images based on pulmonary radiomic filtering',
        journal='Medical Physics',
        cite='49(11):7278–7286',
        doi='10.1002/mp.15837',
        first_author='**Yang Z**; Lafata KJ; Chen X; Bowsher J; Chang Y; Wang C; Y',
        finding='15 mm 滑窗 + 53 个特征做体素级滤波；GLRLM-RunLengthNonUniformity 与 GLCOM-SumAverage 和 PET/SPECT 通气图相关性最高（ρ≈0.45–0.46），优于 HU 阈值法。',
        replicate='✅ 专栏 R1 / 页面「体素级放射组学滤波」',
    ),
    dict(
        year=2022,
        kind='预印本',
        position='★',
        topic=['其他'],
        title='Quantifying U-Net Uncertainty in Multi-Parametric MRI-based Glioma Segmentation by Spherical Image Projection',
        journal='arXiv',
        cite='arXiv:2210.06512（v1 2022-10-12，v3 2023-08-13）',
        doi='10.48550/arXiv.2210.06512',
        first_author='**Yang Z**; Lafata K; Vaios E; Hu Z; Mullikin T; Yin FF; Wan',
        finding='arXiv API 返回；已正式发表（Med Phys 2024;51(3):1931-1943，见 A 区）',
        replicate='—',
    ),
    dict(
        year=2021,
        kind='预印本',
        position='★',
        topic=['其他'],
        title='A Radiomics-Boosted Deep-Learning Model for COVID-19 and Non-COVID-19 Pneumonia Classification Using Chest X-ray Image',
        journal='arXiv',
        cite='arXiv:2107.08667（v1 2021-07-19，v2 2021-10-23）',
        doi='10.48550/arXiv.2107.08667',
        first_author='Hu Z; **Yang Z**; Lafata KJ; Yin FF; Wang C',
        finding='arXiv API 返回；已正式发表（Med Phys 2022;49(5):3213-3222，见 A 区）',
        replicate='—',
    ),
    dict(
        year=2021,
        kind='会议摘要',
        position='○',
        topic=['其他'],
        title='Association Between Dosiomics-Based Index with Radiation Pneumonitis Induced by Radiation Therapy of Breast Cancers',
        journal='Medical Physics（AAPM 2021 年会摘要）',
        cite='48(6)',
        doi='—',
        first_author='**Yang Z**; Chen X; Chen M; Wang C; Yin F',
        finding='Scholars@Duke 出版记录 pid 1495133，NLM 引用格式列出完整作者，Yang Z 居首；DKU/Duke 剂量组学',
        replicate='—',
    ),
    dict(
        year=2021,
        kind='预印本',
        position='★',
        topic=['其他'],
        title='Quantification of lung function on CT images based on pulmonary radiomic filtering',
        journal='arXiv',
        cite='arXiv:2105.11171（v1 2021-05-24，v4 2022-06-24）',
        doi='10.48550/arXiv.2105.11171',
        first_author='**Yang Z**; Lafata KJ; Chen X; Bowsher J; Chang Y; Wang C; Y',
        finding='arXiv API 返回；已正式发表（Med Phys 2022;49(11):7278-7286，见 A 区）',
        replicate='—',
    ),
    dict(
        year=2020,
        kind='学位论文/项目',
        position='★',
        topic=['其他'],
        title='Development of a Voxel-Based Radiomics Calculation Platform for Medical Image Analysis（硕士论文）',
        journal='Duke Kunshan University / Duke University（DukeSpace 机构库）',
        cite='—',
        doi='hdl:10161/20784',
        first_author='**Yang Z**',
        finding="DukeSpace REST API 检索：`dc.contributor.author = Yang, Zhenyu`，`dc.contributor.advisor = Yin, Fang-Fang`，类型 Master's thesi",
        replicate='—',
    ),
    dict(
        year=2020,
        kind='期刊论文',
        position='★',
        topic=['放射组学方法学', '可解释AI'],
        title='Digital phantoms for characterizing inconsistencies among radiomics extraction toolboxes',
        journal='Biomedical Physics & Engineering Express',
        cite='6(2):025016',
        doi='10.1088/2057-1976/ab779c',
        first_author='Chang Y; Lafata K; Wang C; Duan X; Geng R; **Yang Z**; Yin F',
        finding='三家工具箱算出的 61 个特征里，只有 45%–55% 完全一致（CCC=1）；差异来自数学定义、预处理与计算方法。',
        replicate='—（方法学基础，平台在「体素级放射组学滤波」页体现其思想）',
    ),
]

TOPICS = ['不确定性量化', '其他', '分割', '可解释AI', '合成CT', '图像配准', '影像基因组学', '放射组学方法学', '放疗剂量学', '深度学习架构', '生存分析', '肺通气成像', '近距离治疗', '预后预测']

AWARDS = ['AAPM 年会最佳论文摘要奖（Best Paper Abstract Award）', '放射外科学会（RSS）年会培训学员研究成就奖（Trainee Research Achievement Award）']


EARLY_PHYSICS = [
    dict(year=2019, title='Thermodynamic analysis of a long-range interacting spin system', journal='Modern Physics Letters B', cite='33(7):1950072', doi='10.1142/S0217984919500726'),
    dict(year=2019, title='Thermodynamic properties of a long-range interacting Bose system in staggered magnetic field', journal='The European Physical Journal B', cite='92(8):170', doi='10.1140/epjb/e2019-100099-2'),
    dict(year=2019, title="Calculating the ground state energy of hydrogen molecules and helium hydride ions using Bohr's quantum theory", journal='European Journal of Physics', cite='40(6):065405', doi='10.1088/1361-6404/ab32ce'),
    dict(year=2020, title='Shape transformation of red blood cells induced by the osmotic pressure', journal='European Journal of Physics', cite='41(6):065501', doi='10.1088/1361-6404/aba568'),
    dict(year=2020, title='Non-Markovian Mpemba effect in mean-field systems', journal='Physical Review E', cite='101(5):052106', doi='10.1103/PhysRevE.101.052106'),
    dict(year=2022, title='Mpemba effect of a mean-field system: The phase transition time', journal='Physical Review E', cite='105(1):014119', doi='10.1103/PhysRevE.105.014119'),
]


def stats() -> dict:
    from collections import Counter
    kinds = Counter(p["kind"] for p in PUBLICATIONS)
    return {
        "总数": len(PUBLICATIONS),
        "期刊论文": kinds.get("期刊论文", 0),
        "会议摘要": kinds.get("会议摘要", 0),
        "预印本": kinds.get("预印本", 0),
        "学位/项目": kinds.get("学位论文/项目", 0),
        "第一作者": sum(1 for p in PUBLICATIONS if "★" in p["position"]),
        "通讯/末位": sum(1 for p in PUBLICATIONS if "☆" in p["position"]),
        "合作者": sum(1 for p in PUBLICATIONS if "○" in p["position"]),
        "按年份": dict(sorted(Counter(p["year"] for p in PUBLICATIONS).items())),
        "按类型": dict(kinds),
        "按主题": dict(Counter(t for p in PUBLICATIONS for t in p["topic"]).most_common()),
    }
